### ISSUE TITLE
When will a branch with mac support be developed?   

### ISSUE THREAD

**Issue by yiwangsimple** [nullquant/ComfyUI-BrushNet#63]

**Comment by alexcc4** [comment]
mac M3 arm64 error:
`RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.`

**Comment by nullquant** [comment]
Could you please post full ComfyUI log?

**Comment by kkolago** [comment]
On my Mac M2 Max (arm64) I have exactly the same error in node **PowerPaintCLIPLoader**. Fully ComfyUI log is as follows:

> Using split attention in VAE
Using split attention in VAE
Using split attention in VAE
Using split attention in VAE
PowerPaint model type: SD1.5
PowerPaint model file: /Users/chris/git/ComfyUI/models/inpaint/powerpaint/powerpaint_v2.safetensors
PowerPaint model is loaded
clip missing: ['text_projection.weight']
PowerPaint base CLIP file:  /Users/chris/git/ComfyUI/models/clip/model.fp16.safetensors
Successfully add external embeddings: P_ctxt, P_shape, P_obj. current
Successfully add trainable external embeddings: P_ctxt, P_shape, P_obj current
!!! Exception during processing!!! Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
Traceback (most recent call last):
  File "/Users/chris/git/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/Users/chris/git/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/Users/chris/git/ComfyUI/custom_nodes/ComfyUI-0246/utils.py", line 381, in new_func
    res_value = old_func(*final_args, **kwargs)
  File "/Users/chris/git/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/Users/chris/git/ComfyUI/custom_nodes/ComfyUI-BrushNet/brushnet_nodes.py", line 173, in ppclip_loading
    pp_text_encoder.load_state_dict(torch.load(pp_CLIP_file), strict=False)
  File "/Users/chris/git/ComfyUI/venv/lib/python3.10/site-packages/torch/serialization.py", line 1026, in load
    return _load(opened_zipfile,
  File "/Users/chris/git/ComfyUI/venv/lib/python3.10/site-packages/torch/serialization.py", line 1438, in _load
    result = unpickler.load()
  File "/Users/chris/git/ComfyUI/venv/lib/python3.10/site-packages/torch/serialization.py", line 1408, in persistent_load
    typed_storage = load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "/Users/chris/git/ComfyUI/venv/lib/python3.10/site-packages/torch/serialization.py", line 1382, in load_tensor
    wrap_storage=restore_location(storage, location),
  File "/Users/chris/git/ComfyUI/venv/lib/python3.10/site-packages/torch/serialization.py", line 391, in default_restore_location
    result = fn(storage, location)
  File "/Users/chris/git/ComfyUI/venv/lib/python3.10/site-packages/torch/serialization.py", line 266, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "/Users/chris/git/ComfyUI/venv/lib/python3.10/site-packages/torch/serialization.py", line 250, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

**Comment by nullquant** [comment]
Ok, this is something. I don't have access to Mac, so if you will post errors we can try to fix it together. I removed `torch.load`, update and try it.

**Comment by kkolago** [comment]
Thank you. It seems it fixed the issue - there is no error on my Mac now and object removal using PowerPaint v2 works as expected.

**Comment by nullquant** [comment]
Great! That you too.

**Comment by yiwangsimple** [comment]
Great!
